// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leuvmcmhnzxczbilfwhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxldXZtY21obnp4Y3piaWxmd2h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MzU2ODgsImV4cCI6MjA3ODIxMTY4OH0.4uxleizyG-8V0aLLR2MGGZmNUHLK2XJZUMXpsAIp16Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});