// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncuugdfxrnjhexscbfgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdXVnZGZ4cm5qaGV4c2NiZmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMDA4OTcsImV4cCI6MjA4NTg3Njg5N30.7tsqpVA8SA0uDBPGBR47zcv_jG9Uqf8fcXC7z3WQlgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});